services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/wordpress
    depends_on:
      - wordpress
    networks:
      - inception_network
    env_file:
      - .env
    restart: always

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress_data:/var/www/wordpress
    depends_on:
      - mariadb
    networks:
      - inception_network
    env_file:
      - .env
    restart: always

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb_data:/var/lib/mysql
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    networks:
      - inception_network
    env_file:
      - .env
    restart: always

volumes:
  wordpress_data:
    driver: local

  mariadb_data:
    driver: local

networks:
  inception_network:
    driver: bridge
